create sequence permissions_seq start 1 increment 1;
create sequence roles_seq start 1 increment 1;
create sequence tokens_seq start 1 increment 1;
create sequence user_role_permissions_seq start 1 increment 1;
create sequence users_seq start 1 increment 1;
create table permissions (permission_id int8 not null, permission_name varchar(255) not null, primary key (permission_id));
create table roles (role_id int8 not null, role_name varchar(255) not null, primary key (role_id));
create table tokens (token_id int8 not null, access_token varchar(255) not null, refresh_token varchar(255) not null, user_id int8 not null, primary key (token_id));
create table user_role_permissions (user_role_permission_id int8 not null, permission_id int8 not null, role_id int8 not null, user_id int8 not null, primary key (user_role_permission_id));
create table users (user_id int8 not null, email varchar(255) not null, password varchar(255) not null, role varchar(255) not null, username varchar(255) not null, primary key (user_id));
alter table users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table tokens add constraint FK2dylsfo39lgjyqml2tbe0b0ss foreign key (user_id) references users;
alter table user_role_permissions add constraint FKh4baji4ytoa0opkjhpm9yydwf foreign key (permission_id) references permissions;
alter table user_role_permissions add constraint FKme59l67bhp90e42bjtv15squc foreign key (role_id) references roles;
alter table user_role_permissions add constraint FKppqv9rlmheqpwdsa5fvqb74ec foreign key (user_id) references users;
create sequence permissions_seq start 1 increment 1;
create sequence roles_seq start 1 increment 1;
create sequence tokens_seq start 1 increment 1;
create sequence user_role_permissions_seq start 1 increment 1;
create sequence users_seq start 1 increment 1;
create table permissions (permission_id int8 not null, permission_name varchar(255) not null, primary key (permission_id));
create table roles (role_id int8 not null, role_name varchar(255) not null, primary key (role_id));
create table tokens (token_id int8 not null, access_token varchar(255) not null, refresh_token varchar(255) not null, user_id int8 not null, primary key (token_id));
create table user_role_permissions (user_role_permission_id int8 not null, permission_id int8 not null, role_id int8 not null, user_id int8 not null, primary key (user_role_permission_id));
create table users (user_id int8 not null, email varchar(255) not null, password varchar(255) not null, role varchar(255) not null, username varchar(255) not null, primary key (user_id));
alter table users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table tokens add constraint FK2dylsfo39lgjyqml2tbe0b0ss foreign key (user_id) references users;
alter table user_role_permissions add constraint FKh4baji4ytoa0opkjhpm9yydwf foreign key (permission_id) references permissions;
alter table user_role_permissions add constraint FKme59l67bhp90e42bjtv15squc foreign key (role_id) references roles;
alter table user_role_permissions add constraint FKppqv9rlmheqpwdsa5fvqb74ec foreign key (user_id) references users;
create sequence permissions_seq start 1 increment 1;
create sequence roles_seq start 1 increment 1;
create sequence tokens_seq start 1 increment 1;
create sequence user_role_permissions_seq start 1 increment 1;
create sequence users_seq start 1 increment 1;
create table permissions (permission_id int8 not null, permission_name varchar(255) not null, primary key (permission_id));
create table roles (role_id int8 not null, role_name varchar(255) not null, primary key (role_id));
create table tokens (token_id int8 not null, access_token varchar(255) not null, refresh_token varchar(255) not null, user_id int8 not null, primary key (token_id));
create table user_role_permissions (user_role_permission_id int8 not null, permission_id int8 not null, role_id int8 not null, user_id int8 not null, primary key (user_role_permission_id));
create table users (user_id int8 not null, email varchar(255) not null, password varchar(255) not null, role varchar(255) not null, username varchar(255) not null, primary key (user_id));
alter table users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table tokens add constraint FK2dylsfo39lgjyqml2tbe0b0ss foreign key (user_id) references users;
alter table user_role_permissions add constraint FKh4baji4ytoa0opkjhpm9yydwf foreign key (permission_id) references permissions;
alter table user_role_permissions add constraint FKme59l67bhp90e42bjtv15squc foreign key (role_id) references roles;
alter table user_role_permissions add constraint FKppqv9rlmheqpwdsa5fvqb74ec foreign key (user_id) references users;
create sequence permissions_seq start 1 increment 1;
create sequence roles_seq start 1 increment 1;
create sequence tokens_seq start 1 increment 1;
create sequence user_role_permissions_seq start 1 increment 1;
create sequence users_seq start 1 increment 1;
create table permissions (permission_id int8 not null, permission_name varchar(255) not null, primary key (permission_id));
create table roles (role_id int8 not null, role_name varchar(255) not null, primary key (role_id));
create table tokens (token_id int8 not null, access_token varchar(255) not null, refresh_token varchar(255) not null, user_id int8 not null, primary key (token_id));
create table user_role_permissions (user_role_permission_id int8 not null, permission_id int8 not null, role_id int8 not null, user_id int8 not null, primary key (user_role_permission_id));
create table users (user_id int8 not null, email varchar(255) not null, password varchar(255) not null, role varchar(255) not null, username varchar(255) not null, primary key (user_id));
alter table users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table tokens add constraint FK2dylsfo39lgjyqml2tbe0b0ss foreign key (user_id) references users;
alter table user_role_permissions add constraint FKh4baji4ytoa0opkjhpm9yydwf foreign key (permission_id) references permissions;
alter table user_role_permissions add constraint FKme59l67bhp90e42bjtv15squc foreign key (role_id) references roles;
alter table user_role_permissions add constraint FKppqv9rlmheqpwdsa5fvqb74ec foreign key (user_id) references users;
create sequence permissions_seq start 1 increment 1;
create sequence roles_seq start 1 increment 1;
create sequence tokens_seq start 1 increment 1;
create sequence user_role_permissions_seq start 1 increment 1;
create sequence users_seq start 1 increment 1;
create table permissions (permission_id int8 not null, permission_name varchar(255) not null, primary key (permission_id));
create table roles (role_id int8 not null, role_name varchar(255) not null, primary key (role_id));
create table tokens (token_id int8 not null, access_token varchar(255) not null, refresh_token varchar(255) not null, user_id int8 not null, primary key (token_id));
create table user_role_permissions (user_role_permission_id int8 not null, permission_id int8 not null, role_id int8 not null, user_id int8 not null, primary key (user_role_permission_id));
create table users (user_id int8 not null, email varchar(255) not null, password varchar(255) not null, role varchar(255) not null, username varchar(255) not null, primary key (user_id));
alter table users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table tokens add constraint FK2dylsfo39lgjyqml2tbe0b0ss foreign key (user_id) references users;
alter table user_role_permissions add constraint FKh4baji4ytoa0opkjhpm9yydwf foreign key (permission_id) references permissions;
alter table user_role_permissions add constraint FKme59l67bhp90e42bjtv15squc foreign key (role_id) references roles;
alter table user_role_permissions add constraint FKppqv9rlmheqpwdsa5fvqb74ec foreign key (user_id) references users;
create sequence permissions_seq start 1 increment 1;
create sequence roles_seq start 1 increment 1;
create sequence tokens_seq start 1 increment 1;
create sequence user_role_permissions_seq start 1 increment 1;
create sequence users_seq start 1 increment 1;
create table permissions (permission_id int8 not null, permission_name varchar(255) not null, primary key (permission_id));
create table roles (role_id int8 not null, role_name varchar(255) not null, primary key (role_id));
create table tokens (token_id int8 not null, access_token varchar(255) not null, refresh_token varchar(255) not null, user_id int8 not null, primary key (token_id));
create table user_role_permissions (user_role_permission_id int8 not null, permission_id int8 not null, role_id int8 not null, user_id int8 not null, primary key (user_role_permission_id));
create table users (user_id int8 not null, email varchar(255) not null, password varchar(255) not null, role varchar(255) not null, username varchar(255) not null, primary key (user_id));
alter table users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table tokens add constraint FK2dylsfo39lgjyqml2tbe0b0ss foreign key (user_id) references users;
alter table user_role_permissions add constraint FKh4baji4ytoa0opkjhpm9yydwf foreign key (permission_id) references permissions;
alter table user_role_permissions add constraint FKme59l67bhp90e42bjtv15squc foreign key (role_id) references roles;
alter table user_role_permissions add constraint FKppqv9rlmheqpwdsa5fvqb74ec foreign key (user_id) references users;
create sequence permissions_seq start 1 increment 1;
create sequence roles_seq start 1 increment 1;
create sequence tokens_seq start 1 increment 1;
create sequence user_role_permissions_seq start 1 increment 1;
create sequence users_seq start 1 increment 1;
create table permissions (permission_id int8 not null, permission_name varchar(255) not null, primary key (permission_id));
create table roles (role_id int8 not null, role_name varchar(255) not null, primary key (role_id));
create table tokens (token_id int8 not null, access_token varchar(255) not null, refresh_token varchar(255) not null, user_id int8 not null, primary key (token_id));
create table user_role_permissions (user_role_permission_id int8 not null, permission_id int8 not null, role_id int8 not null, user_id int8 not null, primary key (user_role_permission_id));
create table users (user_id int8 not null, email varchar(255) not null, password varchar(255) not null, role varchar(255) not null, username varchar(255) not null, primary key (user_id));
alter table users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table tokens add constraint FK2dylsfo39lgjyqml2tbe0b0ss foreign key (user_id) references users;
alter table user_role_permissions add constraint FKh4baji4ytoa0opkjhpm9yydwf foreign key (permission_id) references permissions;
alter table user_role_permissions add constraint FKme59l67bhp90e42bjtv15squc foreign key (role_id) references roles;
alter table user_role_permissions add constraint FKppqv9rlmheqpwdsa5fvqb74ec foreign key (user_id) references users;
create sequence permissions_seq start 1 increment 1;
create sequence roles_seq start 1 increment 1;
create sequence tokens_seq start 1 increment 1;
create sequence user_role_permissions_seq start 1 increment 1;
create sequence users_seq start 1 increment 1;
create table permissions (permission_id int8 not null, permission_name varchar(255) not null, primary key (permission_id));
create table roles (role_id int8 not null, role_name varchar(255) not null, primary key (role_id));
create table tokens (token_id int8 not null, access_token varchar(255) not null, refresh_token varchar(255) not null, user_id int8 not null, primary key (token_id));
create table user_role_permissions (user_role_permission_id int8 not null, permission_id int8 not null, role_id int8 not null, user_id int8 not null, primary key (user_role_permission_id));
create table users (user_id int8 not null, email varchar(255) not null, password varchar(255) not null, role varchar(255) not null, username varchar(255) not null, primary key (user_id));
alter table users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table tokens add constraint FK2dylsfo39lgjyqml2tbe0b0ss foreign key (user_id) references users;
alter table user_role_permissions add constraint FKh4baji4ytoa0opkjhpm9yydwf foreign key (permission_id) references permissions;
alter table user_role_permissions add constraint FKme59l67bhp90e42bjtv15squc foreign key (role_id) references roles;
alter table user_role_permissions add constraint FKppqv9rlmheqpwdsa5fvqb74ec foreign key (user_id) references users;
create sequence permissions_seq start 1 increment 1;
create sequence roles_seq start 1 increment 1;
create sequence tokens_seq start 1 increment 1;
create sequence user_role_permissions_seq start 1 increment 1;
create sequence users_seq start 1 increment 1;
create table permissions (permission_id int8 not null, permission_name varchar(255) not null, primary key (permission_id));
create table roles (role_id int8 not null, role_name varchar(255) not null, primary key (role_id));
create table tokens (token_id int8 not null, access_token varchar(255) not null, refresh_token varchar(255) not null, user_id int8 not null, primary key (token_id));
create table user_role_permissions (user_role_permission_id int8 not null, permission_id int8 not null, role_id int8 not null, user_id int8 not null, primary key (user_role_permission_id));
create table users (user_id int8 not null, email varchar(255) not null, password varchar(255) not null, role varchar(255) not null, username varchar(255) not null, primary key (user_id));
alter table users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table tokens add constraint FK2dylsfo39lgjyqml2tbe0b0ss foreign key (user_id) references users;
alter table user_role_permissions add constraint FKh4baji4ytoa0opkjhpm9yydwf foreign key (permission_id) references permissions;
alter table user_role_permissions add constraint FKme59l67bhp90e42bjtv15squc foreign key (role_id) references roles;
alter table user_role_permissions add constraint FKppqv9rlmheqpwdsa5fvqb74ec foreign key (user_id) references users;
create sequence permissions_seq start 1 increment 1;
create sequence roles_seq start 1 increment 1;
create sequence tokens_seq start 1 increment 1;
create sequence user_role_permissions_seq start 1 increment 1;
create sequence users_seq start 1 increment 1;
create table permissions (permission_id int8 not null, permission_name varchar(255) not null, primary key (permission_id));
create table roles (role_id int8 not null, role_name varchar(255) not null, primary key (role_id));
create table tokens (token_id int8 not null, access_token varchar(255) not null, refresh_token varchar(255) not null, user_id int8 not null, primary key (token_id));
create table user_role_permissions (user_role_permission_id int8 not null, permission_id int8 not null, role_id int8 not null, user_id int8 not null, primary key (user_role_permission_id));
create table users (user_id int8 not null, email varchar(255) not null, password varchar(255) not null, role varchar(255) not null, username varchar(255) not null, primary key (user_id));
alter table users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table tokens add constraint FK2dylsfo39lgjyqml2tbe0b0ss foreign key (user_id) references users;
alter table user_role_permissions add constraint FKh4baji4ytoa0opkjhpm9yydwf foreign key (permission_id) references permissions;
alter table user_role_permissions add constraint FKme59l67bhp90e42bjtv15squc foreign key (role_id) references roles;
alter table user_role_permissions add constraint FKppqv9rlmheqpwdsa5fvqb74ec foreign key (user_id) references users;
create sequence permissions_seq start 1 increment 1;
create sequence roles_seq start 1 increment 1;
create sequence tokens_seq start 1 increment 1;
create sequence user_role_permissions_seq start 1 increment 1;
create sequence users_seq start 1 increment 1;
create table permissions (permission_id int8 not null, permission_name varchar(255) not null, primary key (permission_id));
create table roles (role_id int8 not null, role_name varchar(255) not null, primary key (role_id));
create table tokens (token_id int8 not null, access_token varchar(255) not null, refresh_token varchar(255) not null, user_id int8 not null, primary key (token_id));
create table user_role_permissions (user_role_permission_id int8 not null, permission_id int8 not null, role_id int8 not null, user_id int8 not null, primary key (user_role_permission_id));
create table users (user_id int8 not null, email varchar(255) not null, password varchar(255) not null, role varchar(255) not null, username varchar(255) not null, primary key (user_id));
alter table users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table tokens add constraint FK2dylsfo39lgjyqml2tbe0b0ss foreign key (user_id) references users;
alter table user_role_permissions add constraint FKh4baji4ytoa0opkjhpm9yydwf foreign key (permission_id) references permissions;
alter table user_role_permissions add constraint FKme59l67bhp90e42bjtv15squc foreign key (role_id) references roles;
alter table user_role_permissions add constraint FKppqv9rlmheqpwdsa5fvqb74ec foreign key (user_id) references users;
create sequence permissions_seq start 1 increment 1;
create sequence roles_seq start 1 increment 1;
create sequence tokens_seq start 1 increment 1;
create sequence user_role_permissions_seq start 1 increment 1;
create sequence users_seq start 1 increment 1;
create table permissions (permission_id int8 not null, permission_name varchar(255) not null, primary key (permission_id));
create table roles (role_id int8 not null, role_name varchar(255) not null, primary key (role_id));
create table tokens (token_id int8 not null, access_token varchar(255) not null, refresh_token varchar(255) not null, user_id int8 not null, primary key (token_id));
create table user_role_permissions (user_role_permission_id int8 not null, permission_id int8 not null, role_id int8 not null, user_id int8 not null, primary key (user_role_permission_id));
create table users (user_id int8 not null, email varchar(255) not null, password varchar(255) not null, role varchar(255) not null, username varchar(255) not null, primary key (user_id));
alter table users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table tokens add constraint FK2dylsfo39lgjyqml2tbe0b0ss foreign key (user_id) references users;
alter table user_role_permissions add constraint FKh4baji4ytoa0opkjhpm9yydwf foreign key (permission_id) references permissions;
alter table user_role_permissions add constraint FKme59l67bhp90e42bjtv15squc foreign key (role_id) references roles;
alter table user_role_permissions add constraint FKppqv9rlmheqpwdsa5fvqb74ec foreign key (user_id) references users;
create sequence permissions_seq start 1 increment 1;
create sequence roles_seq start 1 increment 1;
create sequence tokens_seq start 1 increment 1;
create sequence user_role_permissions_seq start 1 increment 1;
create sequence users_seq start 1 increment 1;
create table permissions (permission_id int8 not null, permission_name varchar(255) not null, primary key (permission_id));
create table roles (role_id int8 not null, role_name varchar(255) not null, primary key (role_id));
create table tokens (token_id int8 not null, access_token varchar(255) not null, refresh_token varchar(255) not null, user_id int8 not null, primary key (token_id));
create table user_role_permissions (user_role_permission_id int8 not null, permission_id int8 not null, role_id int8 not null, user_id int8 not null, primary key (user_role_permission_id));
create table users (user_id int8 not null, email varchar(255) not null, password varchar(255) not null, role varchar(255) not null, username varchar(255) not null, primary key (user_id));
alter table users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table tokens add constraint FK2dylsfo39lgjyqml2tbe0b0ss foreign key (user_id) references users;
alter table user_role_permissions add constraint FKh4baji4ytoa0opkjhpm9yydwf foreign key (permission_id) references permissions;
alter table user_role_permissions add constraint FKme59l67bhp90e42bjtv15squc foreign key (role_id) references roles;
alter table user_role_permissions add constraint FKppqv9rlmheqpwdsa5fvqb74ec foreign key (user_id) references users;
create sequence permissions_seq start 1 increment 1;
create sequence roles_seq start 1 increment 1;
create sequence tokens_seq start 1 increment 1;
create sequence user_role_permissions_seq start 1 increment 1;
create sequence users_seq start 1 increment 1;
create table permissions (permission_id int8 not null, permission_name varchar(255) not null, primary key (permission_id));
create table roles (role_id int8 not null, role_name varchar(255) not null, primary key (role_id));
create table tokens (token_id int8 not null, access_token varchar(255) not null, refresh_token varchar(255) not null, user_id int8 not null, primary key (token_id));
create table user_role_permissions (user_role_permission_id int8 not null, permission_id int8 not null, role_id int8 not null, user_id int8 not null, primary key (user_role_permission_id));
create table users (user_id int8 not null, email varchar(255) not null, password varchar(255) not null, role varchar(255) not null, username varchar(255) not null, primary key (user_id));
alter table users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table tokens add constraint FK2dylsfo39lgjyqml2tbe0b0ss foreign key (user_id) references users;
alter table user_role_permissions add constraint FKh4baji4ytoa0opkjhpm9yydwf foreign key (permission_id) references permissions;
alter table user_role_permissions add constraint FKme59l67bhp90e42bjtv15squc foreign key (role_id) references roles;
alter table user_role_permissions add constraint FKppqv9rlmheqpwdsa5fvqb74ec foreign key (user_id) references users;
create sequence permissions_seq start 1 increment 1;
create sequence roles_seq start 1 increment 1;
create sequence tokens_seq start 1 increment 1;
create sequence user_role_permissions_seq start 1 increment 1;
create sequence users_seq start 1 increment 1;
create table permissions (permission_id int8 not null, permission_name varchar(255) not null, primary key (permission_id));
create table roles (role_id int8 not null, role_name varchar(255) not null, primary key (role_id));
create table tokens (token_id int8 not null, access_token varchar(255) not null, refresh_token varchar(255) not null, user_id int8 not null, primary key (token_id));
create table user_role_permissions (user_role_permission_id int8 not null, permission_id int8 not null, role_id int8 not null, user_id int8 not null, primary key (user_role_permission_id));
create table users (user_id int8 not null, email varchar(255) not null, password varchar(255) not null, role varchar(255) not null, username varchar(255) not null, primary key (user_id));
alter table users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table tokens add constraint FK2dylsfo39lgjyqml2tbe0b0ss foreign key (user_id) references users;
alter table user_role_permissions add constraint FKh4baji4ytoa0opkjhpm9yydwf foreign key (permission_id) references permissions;
alter table user_role_permissions add constraint FKme59l67bhp90e42bjtv15squc foreign key (role_id) references roles;
alter table user_role_permissions add constraint FKppqv9rlmheqpwdsa5fvqb74ec foreign key (user_id) references users;
